### DISCUSSION TITLE
Limit the growth of log files

### DISCUSSION THREAD

**Discussion by WatchLucky** [oceanbase/oceanbase#67] [Q&A] [answered]
The log file keeps increasing   even I do nothing ,   and   "observer.log"   reach    218M after running 30 minute，    is  that right ?   
 
 version ：3.1.0
 
 deploy mode ： mini-single-example.yaml

**Comment by WatchLucky** [comment]
INFO log level

**Comment by frf12** [comment, marked as answer]
Add `syslog_level: WARN` in your yaml. Such as
```yaml
oceanbase-ce:
  servers:    
    - 127.0.0.1
  global:
    syslog_level: WARN
```
If you cluster is runing , you can use `obd cluster edit-config` to edit yaml.
