### ISSUE TITLE
[Bug]: CHAR_LENGTH() output incorrect results when used with subquery

### ISSUE THREAD

**Issue by JZuming** [oceanbase/oceanbase#1029]
### Please check the issue list for the same bug

- [X] I have checked issue list and this bug is encountered for the first time.

### Environment

OB version: 3.1.4-OceanBase CE
OS: CentOS 7

**desploy and start server:**
obd cluster deploy obce-single -c mini-single-example.yaml
obd cluster start obce-single

mini-single-example.yaml: 
```
## Only need to configure when remote login is required
# user:
#   username: your username
#   password: your password if need
#   key_file: your ssh-key file path if need
#   port: your ssh port, default 22
#   timeout: ssh connection timeout (second), default 30
oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
    - 127.0.0.1
  global:
    #  The working directory for OceanBase Database. OceanBase Database is started under this directory. This is a required field.
    home_path: /root/observer
    # The directory for data storage. The default value is $home_path/store.
    # data_dir: /data
    # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
    # redo_dir: /redo
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: lo
    mysql_port: 2881 # External port for OceanBase Database. The default value is 2881. DO NOT change this value after the cluster is started.
    rpc_port: 2882 # Internal port for OceanBase Database. The default value is 2882. DO NOT change this value after the cluster is started.
    zone: zone1
    cluster_id: 1
    # please set memory limit to a suitable value which is matching resource. 
    memory_limit: 20G # The maximum running memory for an observer
    system_memory: 10G # The reserved system memory. system_memory is reserved for general tenants. The default value is 30G.
    stack_size: 512K
    cpu_count: 16
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 268435456
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    # The value of net_thread_count had better be same as cpu's core number. 
    net_thread_count: 4
    major_freeze_duty_time: Disable
    minor_freeze_times: 10
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    datafile_disk_percentage: 20 # The percentage of the data_dir space to the total disk space. This value takes effect only when datafile_size is 0. The default value is 90.
    syslog_level: INFO # System log level. The default value is INFO.
    enable_syslog_wf: false # Print system logs whose levels are higher than WARNING to a separate log file. The default value is true.
    enable_syslog_recycle: true # Enable auto system log recycling or not. The default value is false.
    max_syslog_file_count: 4 # The maximum number of reserved log files before enabling auto recycling. The default value is 0.
    # observer cluster name, consistent with obproxy's cluster_name
    appname: obcluster
    # root_password: # root user password, can be empty
```

### Fast Reproduce Steps(Required)

obclient -h 127.0.0.1 -uroot -P2881 -c -A oceanbase

Input these statements
```
drop table if exists t1;
create table t1 (a int);
insert into t1 values (1), (2);

select CHAR_LENGTH(
  case when 62 <= (
        select a from t1
  ) then '1' else '22' end); --- output 0 or a very large number, e.g. 4038410275

select CHAR_LENGTH('1');   --- output 1
select CHAR_LENGTH('22');  --- output 2
```

### Actual Behavior

The select CHAR_LENGTH(...) outputs a non-deterministic value, for example, 0 or a big number, e.g. 4038410275

### Expected Behavior

The select CHAR_LENGTH(...) should output 1 (or 2), or at least it should print an error.
