### ISSUE TITLE
[Question]: TPCC test pool Performance on 3-replica ob cluster on aws ec2

### ISSUE THREAD

**Issue by jacklanda** [oceanbase/oceanbase#1135]
### Please check the issue list for the same question

- [X] Please try full text in English and attach precise description.

### Describe your question

# TPCC test result
| Connections |    TPmC   |
|:-----------:|:---------:|
|     100     | 15592.000 |
|     500     | 11552.000 |
|     1000    | 10076.000 |

# Cluster Config:
n.b. using `haproxy-2.6.0` instead of `obproxy`.
```yaml
user:
  username: ubuntu
  key_file: {key_file}
  port: 22
  timeout: 30
oceanbase-ce:
  servers:
    - name: server1
      ip: {node_host1}
    - name: server2
      ip: {node_host2}
    - name: server3
      ip: {node_host3}
  global:
    devname: ens5
    memory_limit: 25G 
    memory_limit_percentage: 90
    syslog_io_bandwidth_limit: 10MB
    system_memory: 25G
    datafile_size: 0 
    log_disk_size: 200G 
    syslog_level: PERF 
    enable_syslog_wf: false 
    enable_syslog_recycle: true 
    enable_async_syslog: true
    max_syslog_file_count: 4 
    skip_proxy_sys_private_check: true
    enable_strict_kernel_release: false
  server1:
    mysql_port: 2881
    rpc_port: 2882 
    home_path: /home/ubuntu/observer
    zone: zone1
  server2:
    mysql_port: 2881 
    rpc_port: 2882 
    home_path: /home/ubuntu/observer
    zone: zone2
  server3:
    mysql_port: 2881 
    rpc_port: 2882 
    home_path: /home/ubuntu/observer
    zone: zone3
obagent:
  depends:
    - oceanbase-ce
  servers:
    - name: server1
      ip: {node_host1}
    - name: server2
      ip: {node_host2}
    - name: server3
      ip: {node_host3}
  global:
    home_path: /home/ubuntu/obagent
    ob_monitor_status: active
prometheus:
  depends:
    - obagent
  servers:
    - {prometheus_host}
  global:
    home_path: /home/ubuntu/prometheus
grafana:
  depends:
    - prometheus
  servers:
    - {grafana_host}
  global:
    home_path: /home/ubuntu/grafana
    login_password: ""
```

# Machine Detail:
- obd & tpcc client: aws `c5.4xlarge`: 16 v-cpu cores, 32GB memory, 500GB ssd.
- ob node * 3: aws `c5.4xlarge`: 16 v-cpu cores, 32GB memory, 500GB ssd.
