### ISSUE TITLE
[Bug]: Reduce CPU usage when database is almost empty. 

### ISSUE THREAD

**Issue by longdafeng** [oceanbase/oceanbase#1244]
### Please check the issue list for the same bug

- [X] Please checked issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
- OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
- Hardware parameter:OS type & Compliler & CPU etc. 
- Others

After installation one cluster, the cpu use is almost 1.5 CPU, it should be 0.5 cpu usage by design. 

I don't know wheter it is due to some check sql issued by obagent or not.
```

### Fast Reproduce Steps(Required)

Reprocude steps:
1. choose one ecs 32c128g 
2. install one cluster, there is  one obproxy, one observer, one obagent, one prometheus, one grafana in this cluster
3. create one tenant. 

### Actual Behavior

The CPU usage is almost 1.5
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
15310 longda    20   0 7269440   6.0g  71248 S 158.1  5.1   1847:06 observer
```

### Expected Behavior

The CPU usage should be 0.5

### other information

the configuration:
```
    home_path: /home/longda/ob/observer
    # The directory for data storage. The default value is $home_path/store.
    # data_dir: /data
    # The directory for clog, ilog, and slog. The default value is the same as the data_dir value.
    # redo_dir: /redo
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: em1
    # External port for OceanBase Database. The default value is 2881. DO NOT change this value after the cluster is started.
    # mysql_port: 2881
    # Internal port for OceanBase Database. The default value is 2882. DO NOT change this value after the cluster is started.
    # rpc_port: 2882
    # Defines the zone for an observer. The default value is zone1.
    # zone: zone1
    # The maximum running memory for an observer. When ignored, autodeploy calculates this value based on the current server available resource.
    memory_limit: 58G
    # The percentage of the maximum available memory to the total memory. This value takes effect only when memory_limit is 0. The default value is 80.
    # memory_limit_percentage: 80
    # The reserved system memory. system_memory is reserved for general tenants. The default value is 30G. Autodeploy calculates this value based on the current server     available resource.
    # system_memory: 22G
    # The size of a data file. When ignored, autodeploy calculates this value based on the current server available resource.
    datafile_size: 200G
    # The size of disk space used by the clog files. When ignored, autodeploy calculates this value based on the current server available resource.
    log_disk_size: 66G
    # System log level. The default value is INFO.
    # syslog_level: INFO
    # Print system logs whose levels are higher than WARNING to a separate log file. The default value is true. The default value for autodeploy mode is false.
    # enable_syslog_wf: false
    # Enable auto system log recycling or not. The default value is false. The default value for autodeploy mode is on.
    enable_syslog_recycle: true
    # The maximum number of reserved log files before enabling auto recycling. When set to 0, no logs are deleted. The default value for autodeploy mode is 4.
    # max_syslog_file_count: 4
    # Cluster name for OceanBase Database. The default value is obcluster. When you deploy OceanBase Database and obproxy, this value must be the same as the cluster_name  for obproxy.
    # appname: obcluster
    # Password for root. The default value is empty.
    # root_password:
    # Password for proxyro. proxyro_password must be the same as observer_sys_password. The default value is empty.
    # proxyro_password:
  server1:
    zone: zone1
```
other component's configuration is almost same as default.
