### ISSUE TITLE
[Bug]: OB v4.3.0_CE_BETA 多节点执行结果和单节点/MySQL不一致 （2）

### ISSUE THREAD

**Issue by r33s3n6** [oceanbase/oceanbase#1931]
**Describe the bug**
OB v4.3.0_CE_BETA 多节点执行结果和单节点/MySQL不一致

**Environment**
```
Linux c0bae494cabb 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

commit 0193a343bc60b4699ec47792c3fc4ce166a182f9 (HEAD, tag: v4.3.0_CE_BETA, origin/4.3.0)

observer (OceanBase_CE 4.3.0.1)

REVISION: 1-0193a343bc60b4699ec47792c3fc4ce166a182f9
BUILD_BRANCH: HEAD
BUILD_TIME: Apr  7 2024 14:40:49
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.
```

**Fast Reproduce Steps(Required)**
部署配置文件
```
user:
  username: root
  key_file: private_key
oceanbase-ce:
  servers:
    - name: server1
      ip: 10.0.10.11
    - name: server2
      ip: 10.0.10.12
    - name: server3
      ip: 10.0.10.13
  server1:
    mysql_port: 10000
    rpc_port: 10001
    home_path: /root/data/observer1
    zone: zone1
  server2:
    mysql_port: 10000
    rpc_port: 10001
    home_path: /root/data/observer2
    zone: zone2
  server3:
    mysql_port: 10000
    rpc_port: 10001
    home_path: /root/data/observer3
    zone: zone3
  tag: latest
  include: obd/observer.include.yaml
  global: 
    # for default system config used by farm, please see tools/deploy/obd/observer.include.yaml
    # You can also specify the configuration directly below (stored locally, switching the working directory and redeploying will still take effect)
    production_mode: false
    devname: eth0
    syslog_level: 'WARN'
    syslog_io_bandwidth_limit: '30M'
    log_disk_size: '30G'
    # diag_syslog_per_error_limit: '4'
    max_syslog_file_count: '4'
    cpu_count: '6'
    datafile_size: '10G'
    datafile_next: '5G'
    datafile_maxsize: '30G'
    root_password: ''
    memory_limit: '9G'
    system_memory: '1G'
obproxy-ce:
  servers:
    - 10.0.10.8
  global:
    listen_port: 10004
    prometheus_listen_port: 10005
    syslog_level: 'WARN'
    home_path: /root/data/obproxy
    root_password: ''
  include: obd/obproxy.include.yaml
  depends:
    - oceanbase-ce
 ```

租户配置：
```
DROP TENANT mysql FORCE;
DROP RESOURCE POOL pool_for_tenant_mysql;

CREATE RESOURCE UNIT 4c7g MAX_CPU 4, MIN_CPU 4, MEMORY_SIZE '7G';
create resource pool pool_test unit='4c7g', unit_num=1, zone_list=('zone1' ,'zone2', 'zone3');
create tenant test resource_pool_list=('pool_test'), primary_zone='RANDOM',comment 'test tenant', charset='utf8' set ob_tcp_invited_nodes='%', recyclebin=OFF, ob_query_timeout=5000000;
```

初始化数据库：
[init.sql.txt](https://github.com/oceanbase/oceanbase/files/15022391/init.sql.txt)

出错的SQL语句：
[error.sql.txt](https://github.com/oceanbase/oceanbase/files/15022390/error.sql.txt)

**Expected behavior**
结果保持一致

**Actual Behavior**
[output_replay_mysql.log](https://github.com/oceanbase/oceanbase/files/15022386/output_replay_mysql.log)
[output_replay_ob_main.log](https://github.com/oceanbase/oceanbase/files/15022389/output_replay_ob_main.log)

Oceanbase的第二行的第三列，出现预期之外的NULL
MySQL输出正常。

**Additional Context** 
我们是来自北京航空航天大学网络空间安全学院的BASS团队，主要从事系统软件安全、操作系统和程序分析研究，研发自动化程序测试框架检测软件缺陷。我们使用自研的数据库漏洞测试工具在OceanBase中找到了上述可能的漏洞。
