### ISSUE TITLE
无法安装和启动OCP

### ISSUE THREAD

**Issue by michael-liumh** [oceanbase/oceanbase#2074]
**Describe the bug**

```text
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ocpCeServerApplication'
: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factor
y.BeanCreationException: Error creating bean with name 'ocpStartUpChecker': Invocation of init method failed; nested exc
eption is java.lang.Exception: OCP metadb and server time is not in-sync: db time = 2024-08-03T10:56:29.194Z, server tim
e = 2024-08-03T18:56:29.240Z, max difference allowed is 1000 ms
```

**Environment**

- OS Version and CPU Arch(`uname -a`):
```text
Linux oceanbase-ocp-01 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
```text
observer (OceanBase_CE 4.2.1.2)

REVISION: 102010022023121415-f6752332b5001069034f96c6dbb620926dc666f0
BUILD_BRANCH: HEAD
BUILD_TIME: Dec 14 2023 15:39:00
BUILD_FLAGS: RelWithDebInfo
BUILD_INFO: 

Copyright (c) 2011-present OceanBase Inc.
```

**Fast Reproduce Steps(Required)**

1. sync time clock
```bash
apt install -y chrony
```
2. edit chrony config in server
```bash
sudo sed -ri.ori 's/^(pool.*)/#\1/g' /etc/chrony/chrony.conf
sudo cat << EOF | tee -a /etc/chrony/chrony.conf
server ntp1.aliyun.com iburst minpoll 4 maxpoll 10
server ntp2.aliyun.com iburst minpoll 4 maxpoll 10
server ntp3.aliyun.com iburst minpoll 4 maxpoll 10
server ntp4.aliyun.com iburst minpoll 4 maxpoll 10
server ntp5.aliyun.com iburst minpoll 4 maxpoll 10
local stratum 10
allow 192.168.13.0/24
EOF
```
3. restart chrony in server
```bash
sudo systemctl restart chrony
```
4. check source of time sync
```bash
chronyc sources
```
5. edit chrony config in client
```bash
sudo sed -ri.ori 's/^(pool.*)/#\1/g' /etc/chrony/chrony.conf
sudo echo -e "server 192.168.13.201 iburst\nlocal stratum 10" >> /etc/chrony/chrony.conf
```
6. restart chrony in client
```bash
sudo systemctl restart chrony
```
7. check time sync is ok
```bash
chronyc tracking
```
![image](https://github.com/user-attachments/assets/02366130-8375-4ee1-a243-58552bf20d16)
![image](https://github.com/user-attachments/assets/2a1ef575-f3c5-4e81-a0c2-4fd1b487e193)
![image](https://github.com/user-attachments/assets/276a5e5e-5d5c-4307-811b-54675b490234)
get the result of time sync, that is ok, and then, begin to deploy and start oceanbase and ocp

8. add config file
```yaml
user:
  username: admin
  password:
  port: 22
oceanbase-ce:
  version: 4.2.1.2
  release: 102010022023121415.el7
  package_hash: 1873bbe80cbbe5d00d5f276a4f7302cfca677fb6
  192.168.13.211:
    zone: zone1
    datafile_maxsize: 72287M
    datafile_next: 7229M
  192.168.13.212:
    zone: zone2
    datafile_maxsize: 72338M
    datafile_next: 7234M
  192.168.13.213:
    zone: zone3
    datafile_maxsize: 72341M
    datafile_next: 7234M
  servers:
  - 192.168.13.211
  - 192.168.13.212
  - 192.168.13.213
  global:
    appname: obdemo
    root_password: DG:iD=&,xo3;b#d~X0T9h{/tCHFS
    mysql_port: 2881
    rpc_port: 2882
    home_path: /home/admin/oceanbase
    data_dir: /data/oceanbase/obdemo/observer/data
    redo_dir: /data/oceanbase/obdemo/observer/redo
    devname: eth0
    ocp_meta_tenant:
      tenant_name: ocp_meta
      max_cpu: 1.0
      memory_size: 2G
    ocp_meta_username: root
    ocp_meta_password: =*qMG#i]F8=wwasARtU4
    ocp_meta_db: meta_database
    ocp_monitor_tenant:
      tenant_name: ocp_monitor
      max_cpu: 1.0
      memory_size: 2G
    ocp_monitor_username: root
    ocp_monitor_password: fd.Co223JhaN
    ocp_monitor_db: monitor_database
    cluster_id: 1722707924
    proxyro_password: Az3cy4w2bn
    ocp_root_password: RO6FafM3Qj
    ocp_meta_tenant_log_disk_size: 7680M
    enable_syslog_recycle: true
    enable_syslog_wf: false
    max_syslog_file_count: 4
    memory_limit: 8322M
    datafile_size: 21967M
    system_memory: 2048M
    log_disk_size: 17871M
    cpu_count: 16
    production_mode: false
obproxy-ce:
  version: 4.2.1.0
  package_hash: 0aed4b782120e4248b749f67be3d2cc82cdcb70d
  release: 11.el7
  servers:
  - 192.168.13.201
  global:
    home_path: /home/admin/obproxy
    prometheus_listen_port: 2884
    listen_port: 2883
    obproxy_sys_password: BjjsQXDg6O
    skip_proxy_sys_private_check: true
    enable_strict_kernel_release: false
    enable_cluster_checkout: false
    rs_list: 192.168.13.211:2881;192.168.13.212:2881;192.168.13.213:2881
    observer_sys_password: Az3cy4w2bn
    cluster_name: obdemo
    observer_root_password: DG:iD=&,xo3;b#d~X0T9h{/tCHFS
  depends:
  - oceanbase-ce
ocp-server-ce:
  version: 4.2.2
  package_hash: 84a65bf0ec004e73b772938696b2b896a0ef2b2f
  release: 20240315150922.el7
  servers:
  - 192.168.13.201
  global:
    home_path: /home/admin/ocp
    soft_dir: /home/admin/software
    log_dir: /home/admin/logs
    ocp_site_url: http://192.168.13.201:8080
    port: 8080
    admin_password: d2t5U3xD-twcOGZ3
    memory_size: 4G
    manage_info:
      machine: 10
  depends:
  - oceanbase-ce
  - obproxy-ce
```
9. deploy
```bash
obd cluster deploy obdemo -c obdemo.yaml
```
10. start
```bash
obd cluster start obdemo
```
11. get error log
```text
Search plugins ok
Load cluster param plugin ok
Check before start observer ok
[WARN] OBD-1012: (192.168.13.211) clog and data use the same disk (/data)
[WARN] OBD-1012: (192.168.13.212) clog and data use the same disk (/data)
[WARN] OBD-1012: (192.168.13.213) clog and data use the same disk (/data)

Check before start obproxy ok
[WARN] OBD-4521: The config observer_sys_password in obproxy-ce did not take effect, please config it in oceanbase-ce

Check before start ocp-server ok
Start observer ok
observer program health check ok
Connect to observer 192.168.13.211:2881 ok
Initialize oceanbase-ce ok
Create tenant ocp_meta ok
Create tenant ocp_monitor ok
Start obproxy ok
obproxy program health check ok
Connect to obproxy ok
Initialize obproxy-ce ok
Start ocp-server-ce ok
[ERROR] failed to start 192.168.13.201 ocp-server-ce
[ERROR] start ocp-server-ce failed
[ERROR] ocp-server-ce start failed
```
12. get error log
```bash
less /home/admin/logs/ocp-server.log
```
get the error that I said
```text
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ocpCeServerApplication'
: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factor
y.BeanCreationException: Error creating bean with name 'ocpStartUpChecker': Invocation of init method failed; nested exc
eption is java.lang.Exception: OCP metadb and server time is not in-sync: db time = 2024-08-03T10:56:29.194Z, server tim
e = 2024-08-03T18:56:29.240Z, max difference allowed is 1000 ms
```

**Expected behavior**

no errors
and then, I want to know why is the time sync have problem, before I deploy service, the time sync is ok, why the log said time sync is bad??? 还有为什么日志提示db time刚好落后于server time 8个小时呢？是不是哪里的配置少了一步？？？

**Actual Behavior**

![image](https://github.com/user-attachments/assets/8bd7b76a-939b-4293-9751-8fb08d96b184)

**Additional context**
