### ISSUE TITLE
Cannot do `obd cluster start xx`

### ISSUE THREAD

**Issue by zhangysh1995** [oceanbase/oceanbase#87]
**Describe the bug (__must be provided__)**

I was trying to start the cluster:
````
$ obd cluster start testdb
Get local repositories and plugins ok
[WARN] (127.0.0.1) fs.aio-max-nr must not be less than 1048576 (Current value: 65536)
Start observer ok
observer program health check x
[WARN] failed to start 127.0.0.1 observer
[ERROR] oceanbase-ce start failed
````

**Your Environments (__must be provided__)**

* OS: `CentOS 7, 3.10.0-1160.el7.x86_64`
* Compliler: `gcc/g++ 4.8.5`
* CPU: `Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz`
* Commit id (e.g. `a3ffc7d8`): `12676080774af2940e15911b9f2658f59c52899a`

**How To Reproduce(__must be provided__)**
Just followed the quickstart guide to install odb with yum and deployed a local cluster.

**Expected behavior**
Started.

**Additional context**
My configuration file:
````
user:
  username: 
  password: 

oceanbase-ce:
  servers:
    # Please don't use hostname, only IP can be supported
   - 127.0.0.1
  global:
    home_path: /home/zhangys/observer/
    # Please set devname as the network adaptor's name whose ip is  in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: eth0
    mysql_port: 2883
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    datafile_size: 8G
    # please set memory limit to a suitable value which is matching resource. 
    memory_limit: 8G
    system_memory: 256G
    stack_size: 512K
    cpu_count: 80
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 268435456
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    # The value of net_thread_count had better be same as cpu's core number. 
    net_thread_count: 4
    major_freeze_duty_time: Disable
    minor_freeze_times: 10
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    datafile_disk_percentage: 5
````
